# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Python Mid" # Site name or title, also used in jekyll-seo-tag
description: >- # this means to ignore newlines until "baseurl:"
  Comunidad oficial de Python en México.
logo: "/assets/logos/python.svg" # Site logo, also used in jekyll-seo-tag
url: "https://pythonmid.com" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/daviddarnes/alembic"
email: "me@daviddarnes.com"
twitter_username: python_mid
github_username:  pythonmid

# Build settings
# https://github.com/daviddarnes/alembic
theme: alembic-jekyll-theme
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 9. Site navigation
navigation_header:
- title: Inicio
  url: /
- title: Eventos
  url: /events/
# - title: Blog
#   url: /blog/
# - title: Categories
#   url: /categories/
# - title: Search
#   url: /search/
# - title: Fork Alembic
#   url: https://github.com/daviddarnes/alembic

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: es-Mx # Set the site language

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  X: https://x.com/python_mid
  LinkedIn: https://www.linkedin.com/in/daviddarnes
  GitHub: https://github.com/daviddarnes
  link: https://darn.es
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  facebook: "#3B5998"
  x: "#000000"
  Email: true